import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, Clock3, ExternalLink, MapPin, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { ADDRESS, ADDRESS_TWO, MAPS_LINK, MAPS_LINK_TWO, SiteHeader } from "@/components/site-chrome";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About Bangkok Kropper Barber Shop" },
      { name: "description", content: "The story, standards and people behind Bangkok Kropper Barber Shop." },
      { property: "og:title", content: "About Bangkok Kropper Barber Shop" },
      { property: "og:description", content: "Built on experience. Defined by craft." },
      { property: "og:type", content: "website" },
    ],
  }),
  component: AboutPage,
});

const difference = [
  ["01", "Craftsmanship", "Our team approaches every service with attention to detail, balance and precision. We do not believe in rushing through a service just to move to the next customer."],
  ["02", "Hygiene Without Compromise", "Every customer receives a fresh cape and a new blade where required. Our tools are sanitized using specialized equipment at the appropriate temperatures."],
  ["03", "A Complete Grooming Experience", "Depending on the treatment, customers can experience hot and cold steam, hot and cold facial towels, aftershave application and a gentle refreshing massage."],
  ["04", "Experience Behind Every Chair", "Our founders spent more than a decade working together before creating Kropper. That shared experience is the foundation for the standards we expect from our team."],
  ["05", "Value You Can Feel", "We want customers to leave feeling that the experience genuinely justified the price because of the service, cleanliness, attention and care that came with it."],
] as const;

const process = [
  ["PREPARE", "A fresh cape and a clean environment before every service."],
  ["SANITIZE", "Tools are properly cleaned and sanitized using specialized equipment."],
  ["CRAFT", "Every haircut and grooming service is performed with attention to detail."],
  ["REFINE", "We take the time to make sure the final result is clean, balanced and precise."],
  ["FINISH", "Services are completed with finishing touches designed to leave you feeling refreshed."],
] as const;

const atmosphere = [
  ["MODERN", "A contemporary barber environment designed to feel energetic without feeling overwhelming."],
  ["PROFESSIONAL", "Experienced barbers, disciplined standards and attention to detail."],
  ["WARM", "Professional does not have to mean distant. We want customers to feel welcome and comfortable."],
  ["PRECISE", "From the tools we use to the final finishing touches, detail matters."],
] as const;

const values = [
  ["CRAFT", "We respect the skill behind every cut."],
  ["CLEANLINESS", "Hygiene is not an extra feature. It is a basic responsibility."],
  ["DISCIPLINE", "Consistency comes from standards that are followed every day."],
  ["RESPECT", "Every customer deserves professionalism, attention and genuine care."],
  ["TRUST", "We want customers to feel confident placing their grooming in our hands."],
  ["GROWTH", "We continuously train and improve because great service should never stop evolving."],
] as const;

const branches = [
  { number: "01", name: "Khlong Toei", address: ADDRESS, image: "/4.png", maps: MAPS_LINK },
  { number: "02", name: "Phaya Thai", address: ADDRESS_TWO, image: "/8.png", maps: MAPS_LINK_TWO },
] as const;

function AboutPage() {
  return (
    <div className="about-page min-h-screen bg-background font-sans text-foreground">
      <SiteHeader />
      <main>
        <section className="relative overflow-hidden border-b border-border px-5 py-20 md:py-24">
          <div className="pointer-events-none absolute -right-12 top-20 font-display text-[13rem] leading-none text-primary/[0.035] md:text-[24rem]">01</div>
          <div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
            <div><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">The Kropper Story</p><h1 className="mt-6 max-w-xl font-display text-4xl leading-[0.92] md:text-6xl">Built on Experience.<br /><span className="text-primary">Defined by Craft.</span></h1><p className="mt-7 max-w-lg text-base leading-8 text-muted-foreground">Bangkok Kropper Barber Shop was built by barbers who spent more than a decade mastering the craft together. What began as a shared ambition became a place where skilled hands, serious hygiene and genuine hospitality come together.</p><a href="#story" className="mt-9 inline-flex items-center gap-2 bg-primary px-5 py-3 text-xs font-bold uppercase tracking-[0.16em] text-primary-foreground hover:bg-accent">Discover Our Story <ArrowRight className="size-4" /></a></div>
            <div className="relative min-h-[22rem] overflow-hidden border border-border md:min-h-[30rem]"><img src="/hero.png" alt="Bangkok Kropper Barber Shop" className="size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-background/75 via-transparent to-transparent" /><span className="absolute bottom-5 left-5 border-l-2 border-primary bg-background/75 px-4 py-3 text-xs font-bold uppercase tracking-[0.18em] backdrop-blur-sm">Bangkok Kropper · Est. 2024</span></div>
          </div>
        </section>

        <section id="story" className="border-b border-border bg-secondary/35 px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">02 / Our Story</p><h2 className="mt-5 max-w-md font-display text-4xl leading-[0.95] md:text-6xl">From Experience to Kropper</h2></div><p className="max-w-xl text-base leading-8 text-muted-foreground">A shared career became a shared vision: build a professional barber shop around standards customers can trust.</p></div><div className="relative mt-16 border-l border-primary/60 pl-7 md:ml-[16%] md:pl-12">{[
            ["10+ Years of Experience", "Before Kropper existed, our founders worked together at a renowned barbershop for more than a decade. Those years gave us an understanding of what customers expect from a truly professional barber."],
            ["The Decision", "Mr. Mongkolpat, Mr. Pinit and Mr. Ratchata decided to build something of their own: a shop shaped around their standards of craftsmanship, cleanliness and customer care."],
            ["October 8, 2024", "Bangkok Kropper Barber Shop was born. We brought together our experience, pooled our resources and created a space designed around a professional experience from the moment you walk in until the moment you leave."],
            ["January 20, 2025", "Kropper officially became a registered company. It marked an important step toward building something legitimate, stable and long term, a professional brand with a team and standards customers can trust."],
          ].map(([title, copy], index) => <article key={title} className="relative border-b border-border py-8 first:pt-0 last:border-0"><span className="absolute -left-[2.05rem] top-8 grid size-4 place-items-center rounded-full border border-primary bg-background text-[0.5rem] text-primary md:-left-[3.05rem]">{index + 1}</span><p className="text-xs font-bold uppercase tracking-[0.25em] text-primary">{title}</p><p className="mt-4 max-w-3xl text-base leading-8 text-muted-foreground">{copy}</p></article>)}
        </div></div></section>

        <section className="border-b border-border px-5 py-20 text-center md:py-28"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">03 / Why the Name Kropper?</p><h2 className="mt-5 font-display text-[5rem] leading-[0.8] text-primary sm:text-[8rem] md:text-[12rem]">KROPPER</h2><p className="mx-auto mt-10 max-w-2xl text-base leading-8 text-muted-foreground">A name inspired by the idea of <strong className="text-foreground">cutting, trimming and shaping</strong> whether it is pruning a tree or creating a clean, precise haircut.</p><p className="mx-auto mt-6 max-w-2xl text-sm leading-7 text-muted-foreground">We wanted a name that was distinctive, connected naturally to barbering and represented what we do every day: <span className="font-bold text-primary">cut, shape and refine.</span></p><div className="mt-12 border-t border-border pt-6 text-xs font-bold uppercase tracking-[0.25em] text-primary">Bangkok + Kropper / A barber identity rooted in Bangkok, built around precision.</div></div></section>

        <section className="border-b border-border bg-secondary/35 px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">04 / The Kropper Difference</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">What Makes Kropper Different?</h2></div><div className="mt-12 border-t border-border">{difference.map(([number, title, copy]) => <details key={number} className="group border-b border-border"><summary className="flex cursor-pointer list-none items-center gap-5 py-6"><span className="font-display text-3xl text-primary/60">{number}</span><span className="flex-1 font-display text-2xl text-foreground md:text-3xl">{title}</span><Plus className="size-5 text-primary transition-transform group-open:rotate-45" /></summary><p className="max-w-3xl pb-7 pl-14 text-sm leading-7 text-muted-foreground md:pl-[4.25rem]">{copy}</p></details>)}</div><p className="mt-14 max-w-2xl border-l-2 border-primary pl-5 font-display text-2xl leading-tight text-foreground md:text-4xl">We do not want to be remembered simply as the place where you got a haircut. We want to be remembered as the place where everything felt right.</p></div></section>

        <section className="border-b border-border px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 border-b border-border pb-10 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">05 / The Kropper Standard</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">Every Customer.<br />Every Chair. Every Time.</h2></div><p className="max-w-sm text-sm leading-7 text-muted-foreground">Standards are not claims. They are the steps we repeat until quality becomes part of the experience.</p></div><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-5">{process.map(([title, copy], index) => <div key={title} className="border-t-2 border-primary pt-4"><span className="text-xs font-bold text-primary">0{index + 1}</span><h3 className="mt-6 text-sm font-bold uppercase tracking-[0.16em] text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></div></section>

        <section className="experience-section relative overflow-hidden border-b border-border bg-secondary/35 px-5 py-20 md:py-28"><div className="pointer-events-none absolute -right-24 top-20 size-96 rounded-full border border-primary/15" /><div className="relative mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">06 / The Experience</p><h2 className="mt-5 max-w-2xl font-display text-3xl leading-[0.95] md:text-5xl">It Starts With the Cut.<br /><span className="text-primary">It Ends With How You Feel.</span></h2><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_1.2fr] lg:items-end"><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>We want every customer to feel comfortable, respected and confident from the moment they enter Kropper.</p><p>Whether you are visiting for a quick clean-up, a complete haircut or beard grooming, our goal is to make the experience feel considered rather than rushed.</p><p>You should leave the chair feeling refreshed, confident and satisfied that your time and money were well spent.</p></div><div className="grid grid-cols-1 gap-3 text-center font-display text-2xl text-primary sm:grid-cols-3 md:text-4xl"><span className="border-y border-primary/40 py-6">COMFORT.</span><span className="border-y border-primary/40 py-6">CONFIDENCE.</span><span className="border-y border-primary/40 py-6">CRAFT.</span></div></div></div></section>

        <section className="border-b border-border px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">07 / Atmosphere & Personality</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">The Kropper Character</h2><div className="mt-12 grid border-t border-border sm:grid-cols-2 lg:grid-cols-4">{atmosphere.map(([title, copy]) => <div key={title} className="border-b border-border py-7 sm:px-5 sm:first:pl-0 lg:border-r lg:last:border-r-0"><h3 className="font-display text-3xl text-primary">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{copy}</p></div>)}</div><p className="mt-12 max-w-2xl border-l-2 border-primary pl-5 font-display text-2xl leading-tight md:text-4xl">Kropper is confident without being complicated, professional without losing the human side of barbering.</p></div></section>

        <section className="border-b border-border bg-secondary/35 px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">08 / Our Founders</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">Three Barbers. One Vision.</h2><p className="mt-7 text-base leading-8 text-muted-foreground">The story of Kropper begins with three colleagues who spent more than a decade working together in the barber industry. Over the years, they developed individual skills and a shared understanding of what a great barber shop should be.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[["Mr. Mongkolpat", "/founder1.png"], ["Mr. Pinit", "/founder2.png"], ["Mr. Ratchata", "/founder3.png"]].map(([name, image], index) => <article key={name} className="group relative min-h-[22rem] overflow-hidden border border-border"><img src={image} alt={name} className="size-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent" /><div className="absolute bottom-5 left-5"><span className="text-xs font-bold uppercase tracking-[0.25em] text-primary">0{index + 1} / Founder</span><h3 className="mt-2 font-display text-3xl">{name}</h3></div></article>)}</div><p className="mt-10 text-center font-display text-2xl text-primary md:text-4xl">Different strengths. Shared standards. One Kropper.</p></div></section>

        <section id="locations" className="border-b border-border px-5 py-20 md:py-28"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">09 / Two Branches, One Kropper</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">Different Doors. Same Kropper Experience.</h2><p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-muted-foreground">Bangkok Kropper has two branches, but our identity remains the same across both locations.</p><div className="mx-auto mt-12 grid max-w-4xl gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["SAME CRAFTSMANSHIP", "Precision and quality."], ["SAME HYGIENE STANDARD", "Cleanliness wherever you visit."], ["SAME CUSTOMER CARE", "Attention and respect."], ["SAME KROPPER SPIRIT", "Different locations, one philosophy."]].map(([title, copy]) => <div key={title} className="border-t border-primary px-3 py-5 text-left"><h3 className="text-xs font-bold uppercase tracking-[0.12em] text-primary">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div><div className="mt-14 grid gap-5 text-left lg:grid-cols-2">{branches.map((branch) => <article key={branch.number} className="group grid overflow-hidden border border-border bg-secondary/35 md:grid-cols-[0.8fr_1.2fr]"><div className="relative min-h-56 overflow-hidden"><img src={branch.image} alt={`${branch.name} Bangkok Kropper branch`} className="size-full object-cover transition-transform duration-700 group-hover:scale-105" /><span className="absolute bottom-4 left-4 font-display text-4xl text-primary">{branch.number}</span></div><div className="flex flex-col justify-between p-6"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-primary">Kropper, Branch {branch.number}</p><h3 className="mt-2 font-display text-3xl">{branch.name}</h3><p className="mt-4 flex gap-2 text-sm leading-6 text-muted-foreground"><MapPin className="mt-1 size-4 shrink-0 text-primary" />{branch.address}</p></div><div className="mt-6 flex flex-wrap justify-between gap-3 border-t border-border pt-4"><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground"><Clock3 className="size-4 text-primary" /> 9:00am to 5:00am</span><a href={branch.maps} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-primary">Open Maps <ExternalLink className="size-3.5" /></a></div></div></article>)}</div></div></section>

        <section className="border-b border-border bg-secondary/35 px-5 py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">10 / Our Values</p><h2 className="mt-5 font-display text-3xl leading-[0.95] md:text-5xl">What We Stand For</h2></div><div className="border-t border-border">{values.map(([title, copy], index) => <div key={title} className="flex gap-5 border-b border-border py-5"><span className="w-8 shrink-0 text-[0.68rem] font-bold text-primary">0{index + 1}</span><div><h3 className="font-display text-xl text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div></div>)}</div></div></section>

        <section className="border-b border-border px-5 py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">11 / Officially Kropper</p><h2 className="mt-5 font-display text-3xl leading-[0.95] md:text-5xl">Built to Last.<br />Built Legitimately.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-muted-foreground">Kropper was officially established as a registered company on January 20, 2025, marking an important step in our journey from an independent barber shop into a formally established business.</p><div className="mt-8 grid max-w-md grid-cols-2 gap-4"><div className="border-t-2 border-primary pt-3"><p className="text-[0.68rem] font-bold uppercase tracking-[0.15em] text-primary">Established</p><p className="mt-2 font-display text-xl">08.10.2024</p></div><div className="border-t-2 border-primary pt-3"><p className="text-[0.68rem] font-bold uppercase tracking-[0.15em] text-primary">Registered Company</p><p className="mt-2 font-display text-xl">20.01.2025</p></div></div></div><figure className="overflow-hidden border border-border bg-secondary/35 p-3"><img src="/frame.png%20.jpg" alt="Bangkok Kropper registration document" className="max-h-[34rem] w-full object-contain" /><figcaption className="flex items-center justify-between border-t border-border px-2 pt-3 text-xs font-bold uppercase tracking-[0.15em] text-muted-foreground"><span>Company registration</span><span className="text-primary">Kropper</span></figcaption></figure></div></section>

        <section className="border-b border-border px-5 py-20 md:py-28"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">12 / What We Want You to Remember</p><h2 className="mt-5 font-display text-4xl leading-[0.95] md:text-6xl">Remember the Difference.</h2><div className="mx-auto mt-9 max-w-xl space-y-3 text-base leading-8 text-muted-foreground"><p>We hope you remember more than the haircut.</p><p>Remember the cleanliness. Remember the attention to detail. Remember the feeling of being taken care of. Remember the confidence when you looked in the mirror.</p><p>Remember that the price was not just for a haircut, it was for the experience behind it.</p></div><p className="mx-auto mt-12 max-w-3xl font-display text-3xl leading-tight text-primary md:text-5xl">A Kropper visit should leave you looking sharper, feeling fresher and knowing you chose the right chair.</p></div></section>

        <section className="border-y border-border bg-secondary/35 px-5 py-20 text-center md:py-28"><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-primary">Final Chair Call</p><h2 className="mt-5 font-display text-4xl leading-[0.9] md:text-6xl">Ready for Your Next Cut?</h2><p className="mt-6 text-base text-muted-foreground">Experience the Kropper standard for yourself.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="/book" className="inline-flex items-center gap-2 bg-primary px-5 py-3 text-xs font-bold uppercase tracking-[0.16em] text-primary-foreground hover:bg-accent">Book an Appointment <ArrowRight className="size-4" /></a><a href="/services" className="inline-flex items-center gap-2 border border-border px-5 py-3 text-xs font-bold uppercase tracking-[0.16em] text-foreground hover:border-primary hover:text-primary">Explore Our Services <ArrowRight className="size-4" /></a></div></div></section>
      </main>
    </div>
  );
}
