/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceSlugRouteImport } from './routes/$serviceSlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroomingGuideRouteImport } from './routes/grooming-guide'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BarberJournalArticleSlugRouteImport } from './routes/barber-journal/$articleSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomingGuideRoute = GroomingGuideRouteImport.update({
  id: '/grooming-guide',
  path: '/grooming-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberJournalArticleSlugRoute =
  BarberJournalArticleSlugRouteImport.update({
    id: '/barber-journal/$articleSlug',
    path: '/barber-journal/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/grooming-guide': typeof GroomingGuideRoute
  '/services': typeof ServicesRoute
  '/barber-journal/$articleSlug': typeof BarberJournalArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/grooming-guide': typeof GroomingGuideRoute
  '/services': typeof ServicesRoute
  '/barber-journal/$articleSlug': typeof BarberJournalArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/grooming-guide': typeof GroomingGuideRoute
  '/services': typeof ServicesRoute
  '/barber-journal/$articleSlug': typeof BarberJournalArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/book'
    | '/contact'
    | '/grooming-guide'
    | '/services'
    | '/barber-journal/$articleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/book'
    | '/contact'
    | '/grooming-guide'
    | '/services'
    | '/barber-journal/$articleSlug'
  id:
    | '__root__'
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/book'
    | '/contact'
    | '/grooming-guide'
    | '/services'
    | '/barber-journal/$articleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  GroomingGuideRoute: typeof GroomingGuideRoute
  ServicesRoute: typeof ServicesRoute
  BarberJournalArticleSlugRoute: typeof BarberJournalArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceSlug': {
      id: '/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$serviceSlug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grooming-guide': {
      id: '/grooming-guide'
      path: '/grooming-guide'
      fullPath: '/grooming-guide'
      preLoaderRoute: typeof GroomingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber-journal/$articleSlug': {
      id: '/barber-journal/$articleSlug'
      path: '/barber-journal/$articleSlug'
      fullPath: '/barber-journal/$articleSlug'
      preLoaderRoute: typeof BarberJournalArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  GroomingGuideRoute: GroomingGuideRoute,
  ServicesRoute: ServicesRoute,
  BarberJournalArticleSlugRoute: BarberJournalArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
